services:
  postgres:
    container_name: postgres
    image: postgres:13.0
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jaeger
    restart: always
    ports:
      - "5432:5432"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.57.0
    network_mode: "host"
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
      SPAN_STORAGE_TYPE: 'grpc-plugin'
      GRPC_STORAGE_SERVER: 127.0.0.1:12345
