FROM golang:1.21
WORKDIR /app

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd/jaeger-postgresql ./cmd
COPY ./internal ./internal

EXPOSE 12345 12346

CMD [ "go", "run", "-v", "/app/cmd" ]
