apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-postgresql
  labels:
    component: jaeger-postgresql
spec:
  replicas: 2
  selector:
    matchLabels:
      component: jaeger-postgresql
  template:
    metadata:
      labels:
        component: jaeger-postgresql
    spec:
      containers:
        - name: jaeger-postgresql
          image: "ko://github.com/robbert229/jaeger-postgresql/cmd/jaeger-postgresql"
          args:
            - "--log-level"
            - "warn"
            - "--database.url"
            - "postgresql://postgres:password@localhost:5432/jaeger"
            - "--database.max-conns"
            - "25"
            - "--grpc-server.host-port"
            - "0.0.0.0:12345"
            - "--admin.http.host-port"
            - "0.0.0.0:12346"
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 12345
              protocol: TCP
            - name: metrics
              containerPort: 12346
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jaeger-postgresql-cleaner
  labels:
    component: jaeger-postgresql-cleaner
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Replace"
  jobTemplate:
    metadata:
      name: jaeger-postgresql-cleaner
      labels:
        component: jaeger-postgresql-cleaner
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: jaeger-postgresql-cleaner
            image: "ko://github.com/robbert229/jaeger-postgresql/cmd/jaeger-postgresql-cleaner"
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 250m
                memory: 256Mi
              requests:
                cpu: 250m
                memory: 256Mi