
apiVersion: v1
kind: Service
metadata:
  name: jaeger-postgresql
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "12346"
  labels:
    component: jaeger-postgresql
spec:
  type: ClusterIP
  ports:
  - port: 12345
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 12346
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    component: jaeger-postgresql