apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-postgresql.fullname" . }}
  labels:
    {{- include "jaeger-postgresql.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "12346"
spec:
  type: ClusterIP
  ports:
    - port: 12345
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 12346
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "jaeger-postgresql.selectorLabels" . | nindent 4 }}
