name: docker

on:
    push:
        branches:
            - main
        tags:
            - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - run: docker build -t ghcr.io/robbert229/jaeger-postgresql:${{ github.ref_name }} .
      - run: docker push ghcr.io/robbert229/jaeger-postgresql:${{ github.ref_name }}