name: golang
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16.2
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: jaeger
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod download
      - name: Lint
        run: go vet ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        ueses: nick-fields/retry@v2
        with:
          max_attempts: 3
          command: |
            TEST_DATABASE_URL='postgres://postgres:password@localhost:5432/jaeger' go test -test.parallel=1 ./...
