name: releaser

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
    tags:
      - v*

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - uses: ko-build/setup-ko@v0.6
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          ko resolve --base-import-paths -t ${{ github.ref_name }}  -f k8s/ > release.yaml
      - name: release-notes
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          gh release upload ${{ github.ref_name }} release.yaml